version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sweetalert2
    versions:
    - 10.13.0
    - 10.14.0
    - 10.15.0
    - 10.15.1
    - 10.15.4
    - 10.15.5
    - 10.15.6
    - 10.16.0
    - 10.16.4
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: vue-i18n
    versions:
    - 8.22.4
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: ionicons
    versions:
    - 5.3.0
    - 5.4.0
    - 5.5.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: vuex
    versions:
    - 3.6.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
